###########
# site.title

title:    'Reward-Finder'
subtitle: 'CS 175: Project in AI (in Minecraft)'


#########################
# more settings

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude:
- README.md
- LICENSE.md
